### ISSUE TITLE
winetricks.ps1: ParserError

### ISSUE THREAD

**Issue by esrevinue** [PietJankbal/Chocolatey-for-wine#5] opened 2022-06-24 22:33 UTC
Hello.

I am trying to launch the latest winetricks.ps1 powershell script in order to have a go at fixing a program that is looking for powershell 5.0 and isn't seeming to respond to the current version chocolatey for wine is using. Anyways, when I launch the script from powershell, I get the following error:

`Line |`
`191 |  … -details-target btn-link d-lg-none mt-1 color-fg-inherit">  <svg aria …`
`       |                                                                                              ~`
        `| The '<' operator is reserved for future use.
`

Am I doing anything wrong here?

On wine version 7.11, running as Windows 10, running on a Linux 5.18.6 machine.

Thanks!

**Comment by PietJankbal** [comment] 2022-06-25 16:04
Hi,

Could you tell exact steps you try, because in line 191 in the winetricks script I cannot see that "<" - operator...

Are you trying to install a specific program via chocolatey? If so, could you tell what program, than I could give it a try here.

BTW, if it really needs powershell 5.0 it might be looking for registry key [HKEY_LOCAL_MACHINE\Software\Microsoft\PowerShell\3]
"Install" = dword:00000001

Maybe creating that key manually might help? If so, i could add it to the script.

If that doesn't help either I could try add rudimentary  powershell 5.1  to the script (that's about 15 minutes work i would guess). But as i said, would be handy to know what program exactly you try to install, so i could check if it works

Regards

**Comment by PietJankbal** [comment] 2022-12-09 09:08
Hi, as there`s no update and I cannot reproduce this I'm gonna close this. Feel free to reopen if you still encounter this bug.

**Comment by PietJankbal** [comment] 2022-12-09 09:08
Hi, as there`s no update and I cannot reproduce this I'm gonna close this. Feel free to reopen if you still encounter this bug.

**Closed by PietJankbal** 2022-12-09 09:08 UTC
