### ISSUE TITLE
Virus detected in Chocolatey-for-wine.7z?

### ISSUE THREAD

**Issue by natea11** [PietJankbal/Chocolatey-for-wine#17] opened 2023-10-17 18:03 UTC
I tried to download the 7z file and received a virus notification from Google and Microsoft.  Any idea why?  See below images.  Thanks

<img width="552" alt="image" src="https://github.com/PietJankbal/Chocolatey-for-wine/assets/6468274/519a2569-df7c-4781-951f-f63092906a8c">

<img width="511" alt="image" src="https://github.com/PietJankbal/Chocolatey-for-wine/assets/6468274/38f427ca-8bc3-4561-83c6-0898c3b682eb">

**Comment by PietJankbal** [comment] 2023-10-18 21:58
Hi, 

Thanks for the notification. 

The virus warning is likely caused by the ReflectivePE-Injection script in powershell_codesnippets.ps1
It's really harmless in my script but one can do evil things with it;  I just wanted to added a showcase of what you can do with powershell in wine, but it's detected as virus , so I think I'm  just going to remove it from the script, and readd it as a download, with a warning that it can trigger a virus warning. 

I'll post a notify here when the updated script is released.

Regards

**Comment by PietJankbal** [comment] 2023-10-19 20:24
Hi, I removed part of the script in the newest release, and in instead this is now offered in winetricks.ps1 as a download, so it's not included anymore.
I also added a warning that if you want to download the script with winetricks.ps1, that it might trigger a virus warning.

So this should be fixed I think in the last release ; if it still is an issue, please feel free to reopen this issue

Regarsd

**Closed by PietJankbal** 2023-10-19 20:24 UTC

**Comment by natea11** [comment] 2023-10-19 21:07
Thanks for your help.
